language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -yqq software-properties-common git
  - sudo apt-get install -yqq libopenblas-dev liblapack3 python3-numpy python3-dev swig
  - sudo ln -s /usr/lib/libopenblas.so /usr/lib/libopenblas.so.3
  - wget https://developer.nvidia.com/compute/cuda/8.0/Prod2/local_installers/cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64-deb -O /tmp/cuda.deb
  - sudo dpkg -i /tmp/cuda.deb
  - sudo apt-get -qq update
  - sudo apt-get install -yqq cuda
install:
  - pip install http://download.pytorch.org/whl/cu80/torch-0.2.0.post3-cp36-cp36m-manylinux1_x86_64.whl
  - pip install numpy
  - pip install visdom
# command to run tests
script:
  - pytest ./test